version: "3.9"

networks:
  golang-net:
    name: golang-net
    driver: bridge

services:
  todo-app:
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        - GOLANG_IMAGE=golang:1.21-alpine3.18
    image: todo-app
    container_name: todo_app
    command: ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - migrations
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=qwerty
      - APP_PORT=8000
    networks:
      - golang-net

  db:
    restart: always
    image: postgres:15-alpine3.18
    container_name: app_postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
    networks:
      - golang-net

  migrations:
    image: alpine:3.18
    container_name: app_migrations
    volumes:
      - ../schema:/app
    command: /bin/sh -c "apk update && apk add curl && curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz && ./migrate -path=/app -database=postgres://$$DB_USER:$$DB_PASS@$$DB_HOST:$$DB_PORT/$$DB_NAME?sslmode=disable $$MIGRAT_CMD"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=qwerty
      - MIGRAT_CMD=up
    restart: no
    networks:
      - golang-net
