global:
  scrape_interval: 5s
  scrape_timeout: 4s


scrape_configs:

- job_name: todo-app
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  follow_redirects: false
  static_configs:
  - targets:
    - todo-app:8000
    labels:
      ms: todo-app
